version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URL=${MONGO_URL}
      - CLIENT_URL=${CLIENT_URL}
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - backend

  client:
    build:
      context: ./client
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    networks:
      - frontend

volumes:
  mongo_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
